# Generated by Django 4.2.7 on 2023-12-08 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultant',
            name='availability',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='consultant',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='consultant',
            name='certifications',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='consultant',
            name='languages_spoken',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='normaluser',
            name='interests',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='normaluser',
            name='preferred_language',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='users',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='BookedConsultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_time', models.DateTimeField()),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.consultant')),
                ('normal_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.normaluser')),
            ],
        ),
        migrations.AddField(
            model_name='normaluser',
            name='booked_consultations',
            field=models.ManyToManyField(through='accounts.BookedConsultation', to='accounts.consultant'),
        ),
    ]
