# Generated by Django 4.2.7 on 2023-12-10 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_consultant_availability_consultant_bio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='tc',
        ),
    ]
