# Generated by Django 4.2.7 on 2024-02-01 15:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarSlot',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('start_time', models.DateTimeField(help_text='Start time for the slot.')),
                ('end_time', models.DateTimeField(help_text='End time for the slot')),
                ('duration', models.DurationField(help_text='Duration of the slot')),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Booked', 'Booked'), ('Cancelled', 'Cancelled')], default='Available', max_length=10)),
                ('recurring', models.BooleanField(default=False, help_text='Is this a recurring event?')),
                ('belongs_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_slots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SlotBooking',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('booked_at', models.DateTimeField(auto_now_add=True, help_text='Date and time of booking')),
                ('description', models.TextField(help_text='Additional info about the booking', max_length=1012, null=True)),
                ('cancellation_reason', models.TextField(blank=True, help_text='Reason for cancellation', null=True)),
                ('booked_by', models.ForeignKey(help_text='User who booked the slot.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booked_slots', to=settings.AUTH_USER_MODEL)),
                ('slot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='booking_details', to='calendly.calendarslot')),
            ],
            options={
                'ordering': ['-booked_at'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('availability', models.TextField(help_text="User's general availability")),
                ('timezone', models.CharField(default='UTC', help_text="User's timezone", max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendly_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
