# Generated by Django 4.2.7 on 2024-02-06 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('consultant', 'Consultant'), ('client', 'Client'), ('admin', 'Admin')], max_length=10),
        ),
    ]
